package org.josht.utils.math
{
	/**
	 * Tests equality for numbers that may have been generated by faulty floating point math.
	 * This is not an issue exclusive to the Flash Player, but all modern computing in general.
	 * The value is generally offset by an insignificant fraction, and it may be corrected.
	 * 
	 * <p>Alternatively, this function could be used for other purposes than to correct floating
	 * point errors. Certainly, it could determine if two very large numbers are within a certain
	 * range of difference. This might be useful for determining "ballpark" estimates or similar
	 * statistical analysis that may not need complete accuracy.</p>
	 * 
	 * @param		number1		the first number to test
	 * @param		number2		the second number to test
	 * @param		precision	the number of digits in the fractional portion to keep
	 * @return		true, if the numbers are close enough to be considered equal, false if not.
	 */
	public function fuzzyEquals(number1:Number, number2:Number, precision:int = 5):Boolean
	{
		var difference:Number = number1 - number2;
		var range:Number = Math.pow(10, -precision);
		
		//default precision checks the following:
		//0.00001 < difference > -0.00001
		
		return difference < range && difference > -range;
	}
}